name: Build Documentation HTML

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies and packages
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install build
        pip install .
        python -m pip install matplotlib furo m2r2 sphinx sphinx_pyproject
    - name: Build Document
      working-directory: docs/
      run: make html
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: docs/build/html/ # The folder the action should deploy.
